[programs.localnet]
mysolanaapp = "H5BpnRAYnpnfbCxVU6ZzdpzoRrtHzonuTT4GsA7vsoQX"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/dannybin/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
